name: Daily Bugle

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: List files in root
      run: ls -R

    - name: List files in .github
      run: ls -R .github

    - name: List files in .github/actions
      run: ls -R .github/actions

    - name: List files in .github/actions/checkout
      run: ls -R .github/actions/checkout

    - name: Run update script
      run: ./src/daily_bugle.sh

    - name: Commit changes
      env: 
        ACTIONS_WORKFLOW: ${{ secrets.ACTIONS_WORKFLOW }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email '61887712+SysHarmonics@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_WORKFLOW }}@github.com/${{ github.repository }}
        git add README.md
        git commit -m "Daily Bugle" --allow-empty
        git push